# 使用前请阅读文档：https://bili33.top/posts/MHYY-AutoCheckin-Manual-Gen2/
# 有问题请前往Github开启issue：https://github.com/GamerNoTitle/MHYY/issues

######## 以下为账号配置项，可以多账号，详情请参考文档 ########
accounts:
  # 第一个账号
  - token: ai=4;ci=1;oi=323997479;ct=v2_4e6cf3dd8def51e39529b1c48b8c7a2b9a21e5e4;si=1c25e100b0979be4e0e25c2e28e861bb03ab708358467343071cdede9fb46cfa;bi=hk4e_cn
    # 关于type：如果你在安卓版的云·原神里面抓的话type应该是2
    # 如果你是网页版抓的，那type应该是16
    # 此处仅供参考，具体以你抓的为准 
    type: 16
    # sysver：如果你是安卓版抓的，这个应该会显示你的安卓版本（鸿蒙不清楚，手上没设备）
    # 如果你是网页版抓的，这个应该是你的系统版本（注：Windows 10和Windows 11都是写的Windows 10）
    sysver: Windows 10
    # deviceid：手机抓的会有这个，抓到什么填什么
    # 如果是网页版抓的，那也是抓到什么填什么
    deviceid: 84300a1d-0411-43b9-bc03-f32836dda16a
    # devicename: 手机抓的话就是手机的入网型号，如红米K40为M2012K11AC，红米K50为22021211RC
    # 如果是网页版抓的，填Unknown
    devicename: Unknown
    # devicemodel: 手机抓的填抓出来的手机型号，大概为手机厂商+上面的deviceid，如红米K40为Xiaomi M2012K11AC
    # 如果是网页版抓的，填Unknown
    devicemodel: Unknown
    # appid: 国服手机抓的固定填1953439974，网页版抓的留空；国际服手机抓的填600493
    appid: 
    # region(可选): 账号所处的地区，国服填cn，国际服填os，不填或非法值按国服处理
    region: cn
